version: '3.7'
services:
  db:
    container_name: couchbaseservice
    build:
      context: couchbase/.
    image: couchbaseservice:latest
    restart: always
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    networks:
      - spring-todo-app-network

networks:
  spring-todo-app-network:
    driver: bridge