version: '3.7'
services:
  todo-couchbase:
    container_name: todo-couchbase
    build: user/
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: Administrator
      COUCHBASE_ADMINISTRATOR_PASSWORD: password
      COUCHBASE_BUCKET: todo-user
      COUCHBASE_BUCKET_PASSWORD: password
    networks:
      - spring-todo-app-network
networks:
  spring-todo-app-network:
    driver: bridge